#!/bin/bash

command -v git >/dev/null 2>&1  || { echo >&2 "I require git but it's not installed. I'm just gonna back away slowly..."; exit 1; }

echo "Okay, here's what I'll do for you:"
echo ""
echo "npm run build"
echo ""
echo "git add ."
echo "git commit -m \"${1}\""
echo "git push"
echo ""
echo "scp -r public/ ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf"
echo "scp -r src/ ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf"
echo "scp -r index.html ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf"
echo "scp -r server.js ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf"
echo "scp -r package.json ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf"
echo ""
echo "ssh ubuntu@omniwolf.io"
echo "cd app-omniwolf"
echo "sudo forever stop server.js"
echo "npm install"
echo "sudo forever start server.js"
echo ""
read -p "Press [Enter] key to continue... "

npm run build

git add .
git commit -m "${1}"
git push

scp -r public/ ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf
scp -r src/ ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf
scp -r index.html ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf
scp -r server.js ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf
scp -r package.json ubuntu@omniwolf.io:/home/ubuntu/app-omniwolf

ssh ubuntu@omniwolf.io <<-'ENDSSH'
  cd app-omniwolf
  sudo forever stop server.js
  npm install
  sudo forever start server.js
ENDSSH
