#!/bin/bash

command -v git >/dev/null 2>&1  || { echo >&2 "I require git but it's not installed. I'm just gonna back away slowly..."; exit 1; }

echo "Okay, here's what I'll do for you:"
echo ""
echo "webpack"
echo "git add ."
echo "git commit -m \"wsshing\""
echo "git push"
echo "scp -r dist/. ubuntu@52.36.92.204:/var/www/html/"
echo ""
read -p "Press [Enter] key to continue... "
webpack
git add .
git commit -m "wsshing"
git push
scp -r dist/. ubuntu@52.36.92.204:/var/www/html/
